version: '3'
services:
  web:
    build: .
    image: coelis/invoiceplane
    env_file: .env.production
    ports:
    - "5000:80"
    volumes:
    - ./data/logs/:/var/log
    - ./data/uploads/:/app/uploads
    depends_on:
    - mariadb
    cap_add:
    - SYS_PTRACE
  mariadb:
    image: mariadb
    env_file: .env.production
    volumes:
      - ./data/mysql/:/var/lib/mysql
